### ISSUE TITLE
Website link no longer works

### ISSUE THREAD

**Issue by webprofusion-chrisc** [bgins/coincident-spectra#15]
The github repo currently points to [coincident-spectra.fission.app/](https://coincident-spectra.fission.app/) which doesn't appear to be a valid domain anymore. Suggest switching it to github pages.

**Comment by bgins** [comment]
Hey @webprofusion-chrisc! Thanks for opening the issue. ❤️ 

Yeah, Fission hosting has come to an end, and I need to get this deployed elsewhere. Will look at GitHub pages as a possibility. Also have a few other web audio apps that are served direct from AWS S3, so might go that route.

Hope to get time for it this weekend. Thanks again for raising the issue! 🙌

**Comment by bgins** [comment]
@webprofusion-chrisc I've republished the site at https://coincident-spectra.brianginsburg.com/

Also have a PR in to update the Elementary showcase link pointing to it: https://github.com/elemaudio/website/pull/14

Thanks again for calling it to my attention. Much appreciated! 🙏
